apiVersion: apps/v1
kind: Deployment
metadata:
  name: faucet
  namespace: faucet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faucet
  template:
    metadata:
      labels:
        app: faucet
    spec:
      containers:
        - name: faucet
          image: docker.io/faucet/faucet:latest
          ports:
            - containerPort: 6653
