kind: Service
apiVersion: v1
metadata:
  name:  bgp-lb
  namespace: faucet
  # annotations:
    # metallb.universe.tf/loadBalancerIPs: 192.168.1.67
spec:
  selector:
    app: faucet
  type:  LoadBalancer
  ports:
  - name:  openflow
    port:  9179
    targetPort:  9179
