apiVersion: v1
kind: Service
metadata:
  name: bgp
  namespace: faucet
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: faucet
  ports:
    - port: 9179
      targetPort: 9179
      nodePort: 30001
  externalIPs:
    - 192.168.10.66