kind: Service
apiVersion: v1
metadata:
  name:  faucet-openflow
  namespace: faucet
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.65
spec:
  selector:
    app: faucet
  type:  LoadBalancer
  ports:
  - name:  openflow
    port:  6653
    targetPort:  6653